// ==========================================================
// 世界地図モード専用の追加地域データ
// 国旗クイズ・首都クイズの対象(js/countries.js の198件)には
// 一切含めない。地図モードの探索対象としてのみ追加する。
// mapOnly:true / quizEligible:false を必ず持たせ、
// quiz.js側のロジックが誤ってこれらを問題に含めないようにする。
// ==========================================================

const MAP_ONLY_REGIONS = [
  {
    id: "gl",
    name: "グリーンランド",
    englishName: "Greenland",
    region: "namerica",
    regionJa: "北アメリカ・中央アメリカ・カリブ",
    flag: "./assets/flags/gl.svg",
    aliases: ["グリーンランド", "Greenland"],
    mapCode: "GRL",
    lat: 71.7,
    lng: -42.6,
    infoLabel: "中心都市",
    infoValue: "ヌーク",
    description: "グリーンランドは世界最大の島で、大部分が氷床に覆われています。デンマーク王国を構成する自治領で、中心都市はヌークです。",
    mapOnly: true,
    quizEligible: false,
  },
  {
    id: "hk",
    name: "香港",
    englishName: "Hong Kong",
    region: "asia",
    regionJa: "アジア",
    flag: "./assets/flags/hk.svg",
    aliases: ["香港", "ホンコン", "Hong Kong"],
    mapCode: "HKG",
    lat: 22.3,
    lng: 114.2,
    infoLabel: "区分",
    infoValue: "中国の特別行政区",
    description: "香港は中国南部に位置する特別行政区で、独自の行政・経済制度を持つ国際的な金融都市です。",
    mapOnly: true,
    quizEligible: false,
  },
  {
    id: "mo",
    name: "マカオ",
    englishName: "Macao",
    region: "asia",
    regionJa: "アジア",
    flag: "./assets/flags/mo.svg",
    aliases: ["マカオ", "Macao", "Macau"],
    mapCode: "MAC",
    lat: 22.2,
    lng: 113.5,
    infoLabel: "区分",
    infoValue: "中国の特別行政区",
    description: "マカオは中国南部に位置する特別行政区で、かつてポルトガルの統治下にありました。カジノ産業で知られています。",
    mapOnly: true,
    quizEligible: false,
  },
  {
    id: "fo",
    name: "フェロー諸島",
    englishName: "Faroe Islands",
    region: "europe",
    regionJa: "ヨーロッパ",
    flag: "./assets/flags/fo.svg",
    aliases: ["フェロー諸島", "Faroe Islands"],
    mapCode: "FRO",
    lat: 62.0,
    lng: -6.8,
    infoLabel: "中心都市",
    infoValue: "トースハウン",
    description: "フェロー諸島は北大西洋に浮かぶ島々で、デンマーク王国を構成する自治領です。中心都市はトースハウンです。",
    mapOnly: true,
    quizEligible: false,
  },
  {
    id: "hawaii",
    name: "ハワイ",
    englishName: "Hawaii",
    region: "namerica",
    regionJa: "北アメリカ・中央アメリカ・カリブ",
    flag: "./assets/flags/hi.svg",
    aliases: ["ハワイ", "Hawaii"],
    mapCode: "HI",
    lat: 21.3,
    lng: -157.85,
    infoLabel: "区分",
    infoValue: "アメリカ合衆国の州",
    // アメリカ合衆国(countries.jsのid「us」)が選択された際、本土・アラスカと
    // 一緒にハワイもオレンジ色にするための対応付け。ハワイ単独で選択された
    // 場合は、この値に関わらずハワイの実ポリゴンだけがオレンジになる
    parentQuizId: "us",
    description: "ハワイはアメリカ合衆国の州で、太平洋に浮かぶ火山島群です。美しいビーチと火山で知られる人気の観光地です。",
    mapOnly: true,
    quizEligible: false,
  },
  {
    id: "guam",
    name: "グアム",
    englishName: "Guam",
    region: "oceania",
    regionJa: "オセアニア",
    flag: "./assets/flags/gu.svg",
    aliases: ["グアム", "Guam"],
    mapCode: "GUM",
    lat: 13.44,
    lng: 144.79,
    infoLabel: "区分",
    infoValue: "アメリカ合衆国の準州",
    description: "グアムは太平洋のミクロネシアに位置するアメリカ合衆国の準州です。日本から近いリゾート地として知られています。",
    mapOnly: true,
    quizEligible: false,
  },
  {
    id: "curacao",
    name: "キュラソー",
    englishName: "Curaçao",
    region: "namerica",
    regionJa: "北アメリカ・中央アメリカ・カリブ",
    flag: "./assets/flags/cw.svg",
    aliases: ["キュラソー", "Curacao", "Curaçao"],
    mapCode: "CUW",
    lat: 12.12,
    lng: -68.93,
    infoLabel: "区分",
    infoValue: "オランダ王国を構成する国",
    description: "キュラソーはカリブ海に浮かぶ島で、オランダ王国を構成する国の一つです。カラフルな町並みで知られています。",
    mapOnly: true,
    quizEligible: false,
  },
  {
    id: "nc",
    name: "ニューカレドニア",
    englishName: "New Caledonia",
    region: "oceania",
    regionJa: "オセアニア",
    flag: "./assets/flags/nc.svg",
    aliases: ["ニューカレドニア", "New Caledonia"],
    mapCode: "NCL",
    lat: -21.3,
    lng: 165.5,
    infoLabel: "中心都市",
    infoValue: "ヌメア",
    description: "ニューカレドニアは南太平洋にあるフランスの特別な地位を持つ地域です。独自の政府と議会があり、中心都市はヌメアです。",
    mapOnly: true,
    quizEligible: false,
  },
  {
    id: "fk",
    name: "フォークランド諸島",
    englishName: "Falkland Islands",
    region: "samerica",
    regionJa: "南アメリカ",
    flag: "./assets/flags/fk.svg",
    aliases: ["フォークランド諸島", "フォークランド", "マルビナス諸島", "Falkland Islands", "Malvinas"],
    mapCode: "FLK",
    lat: -51.7,
    lng: -59.0,
    infoLabel: "中心都市",
    infoValue: "スタンリー",
    description: "フォークランド諸島は南大西洋にある島々で、現在はイギリスの海外領土として統治されています。主権をめぐってイギリスとアルゼンチンの間に争いがあります。",
    mapOnly: true,
    quizEligible: false,
  },
  {
    id: "tf",
    name: "フランス領南方・南極地域",
    englishName: "French Southern and Antarctic Lands",
    region: "africa",
    regionJa: "アフリカ",
    flag: "./assets/flags/tf.svg",
    aliases: [
      "フランス領南方・南極地域",
      "フランス領南方地域",
      "French Southern and Antarctic Lands",
      "French Southern Territories",
      "TAAF",
      "ケルゲレン諸島",
    ],
    mapCode: "ATF",
    lat: -49.35,
    lng: 69.2,
    infoLabel: "区分",
    infoValue: "フランスの海外領域",
    description: "フランス領南方・南極地域は、ケルゲレン諸島など5つの地区からなるフランスの海外領域です。科学研究や自然環境の保護が行われています。この世界地図では主にケルゲレン諸島が表示されます。",
    mapOnly: true,
    quizEligible: false,
  },
  {
    id: "gs",
    name: "サウスジョージア・サウスサンドウィッチ諸島",
    englishName: "South Georgia and the South Sandwich Islands",
    region: "samerica",
    regionJa: "南アメリカ",
    flag: "./assets/flags/gs.svg",
    aliases: [
      "サウスジョージア・サウスサンドウィッチ諸島",
      "サウスジョージア",
      "South Georgia",
      "South Georgia and the South Sandwich Islands",
    ],
    mapCode: "SGS",
    lat: -54.3,
    lng: -36.5,
    infoLabel: "行政拠点",
    infoValue: "キング・エドワード・ポイント",
    description: "南大西洋にあるイギリスの海外領土です。ペンギンやアザラシなど多くの野生生物が生息し、自然保護や科学研究の重要な地域になっています。",
    mapOnly: true,
    quizEligible: false,
  },
  {
    id: "nu",
    name: "ニウエ",
    englishName: "Niue",
    region: "oceania",
    regionJa: "オセアニア",
    flag: "./assets/flags/nu.svg",
    aliases: ["ニウエ", "Niue"],
    mapCode: "NIU",
    lat: -19.05,
    lng: -169.87,
    infoLabel: "中心都市",
    infoValue: "アロフィ",
    description: "ニウエは南太平洋のポリネシアにある島で、1974年からニュージーランドとの自由連合による自治国です。中心都市はアロフィです。",
    mapOnly: true,
    quizEligible: false,
  },
  {
    id: "ck",
    name: "クック諸島",
    englishName: "Cook Islands",
    region: "oceania",
    regionJa: "オセアニア",
    flag: "./assets/flags/ck.svg",
    aliases: ["クック諸島", "Cook Islands"],
    mapCode: "COK",
    lat: -21.21,
    lng: -159.78,
    infoLabel: "中心都市",
    infoValue: "アバルア",
    description: "クック諸島は南太平洋にある15の島からなり、ニュージーランドとの自由連合による自治国です。中心都市アバルアはラロトンガ島にあります。",
    mapOnly: true,
    quizEligible: false,
  },
  {
    id: "eh",
    name: "西サハラ",
    englishName: "Western Sahara",
    region: "africa",
    regionJa: "アフリカ",
    flag: "./assets/flags/eh.svg",
    aliases: ["西サハラ", "Western Sahara", "Sahara Occidental"],
    mapCode: "ESH",
    lat: 24.2,
    lng: -13.0,
    infoLabel: "区分",
    infoValue: "国連の非自治地域",
    description: "西サハラはアフリカ北西部にある地域で、国連の非自治地域リストに1963年から掲載されています。最終的な政治的地位をめぐる問題は現在も解決していません。",
    mapOnly: true,
    quizEligible: false,
  },
];
